---
- hosts: test-servers
  sudo: true
  pre_tasks:
    - apt: update_cache=yes
  roles:
    - pipeline2
  vars:
    pipeline2_extra_modules:
      - name: mod-celia
        version: 1.4.0
        type: maven
        maven_coords: {g: org.daisy.pipeline.modules.braille, a: mod-celia, c: all}
        md5: 1d433dacbb1d0bb7e1cc10ab3e118ae7
      - name: mod-dedicon
        version: 1.6.0
        type: maven
        maven_coords: {g: org.daisy.pipeline.modules.braille, a: mod-dedicon, c: all}
        md5: 834331c6536f41c51bd2a8e37dde1789
      - name: mod-mtm
        version: 1.6.1
        type: maven
        maven_coords: {g: org.daisy.pipeline.modules.braille, a: mod-mtm, c: all}
        md5: ee09c86858173c8d9897ad5c34d71f2c
      - name: mod-nlb
        version: 1.9.0
        type: maven
        maven_coords: {g: org.daisy.pipeline.modules.braille, a: mod-nlb, c: all}
        md5: 414889231ee6ab79c9e75205a324fa47
      - name: mod-nota
        version: 1.3.3
        type: maven
        maven_coords: {g: org.daisy.pipeline.modules.braille, a: mod-nota, c: all}
        md5: feea26d1a79c4194ade73ddc05c8bec9
      - name: mod-sbs
        version: 1.8.0
        type: maven
        maven_coords: {g: org.daisy.pipeline.modules.braille, a: mod-sbs, c: all}
        md5: 111cfd7ffa7853e65c4a2ac959a2817f

