---
- include_vars: debs.yml
- apt:
    pkg: openjdk-7-jre
    state: installed
- file:
    path: /tmp/debs
    state: directory
- copy:
    src: "{{ item }}"
    dest: /tmp/debs/
  with_items:
    - "debs/org/daisy/pipeline/assembly/{{ engine_version }}/assembly-{{ engine_version }}-all.deb"
    - "debs/org/daisy/pipeline/assembly/{{ webui_version }}/assembly-{{ webui_version }}-webui_all.deb"
    - "debs/org/daisy/pipeline/modules/braille/mod-celia/{{ mod_celia_version }}/mod-celia-{{ mod_celia_version }}-all.deb"
    - "debs/org/daisy/pipeline/modules/braille/mod-dedicon/{{ mod_dedicon_version }}/mod-dedicon-{{ mod_dedicon_version }}-all.deb"
    - "debs/org/daisy/pipeline/modules/braille/mod-mtm/{{ mod_mtm_version }}/mod-mtm-{{ mod_mtm_version }}-all.deb"
    - "debs/org/daisy/pipeline/modules/braille/mod-nlb/{{ mod_nlb_version }}/mod-nlb-{{ mod_nlb_version }}-all.deb"
    - "debs/org/daisy/pipeline/modules/braille/mod-nota/{{ mod_nota_version }}/mod-nota-{{ mod_nota_version }}-all.deb"
    - "debs/org/daisy/pipeline/modules/braille/mod-sbs/{{ mod_sbs_version }}/mod-sbs-{{ mod_sbs_version }}-all.deb"
- shell: DEBIAN_FRONTEND=noninteractive dpkg -i /tmp/debs/*.deb
- service:
    name: "{{ item }}"
    state: started
  with_items:
    - pipeline2d
    - pipeline2-webuid
