---
- include_vars: versions.yml
- apt:
    pkg: openjdk-7-jre
    state: installed
- file:
    path: /tmp/debs
    state: directory
- copy:
    src: "{{ item }}"
    dest: /tmp/debs/
  with_items:
    - "debs/engine-{{ engine_version }}.deb"
    - "debs/webui-{{ webui_version }}.deb"
    - "debs/mod-celia-{{ mod_celia_version }}.deb"
    - "debs/mod-dedicon-{{ mod_dedicon_version }}.deb"
    - "debs/mod-mtm-{{ mod_mtm_version }}.deb"
    - "debs/mod-nlb-{{ mod_nlb_version }}.deb"
    - "debs/mod-nota-{{ mod_nota_version }}.deb"
    - "debs/mod-sbs-{{ mod_sbs_version }}.deb"
# remove database
- file:
    path: /var/opt/daisy-pipeline2
    state: absent
- shell: DEBIAN_FRONTEND=noninteractive dpkg -i /tmp/debs/*.deb
- service:
    name: "{{ item }}"
    state: started
  with_items:
    - pipeline2d
    - pipeline2-webuid
