---
- apt_repository:
    repo: 'deb http://ppa.launchpad.net/openjdk-r/ppa/ubuntu precise main'
    state: present
- apt:
    pkg: openjdk-8-jre
    state: installed
    force: yes
- file:
    path: /tmp/debs
    state: absent
- file:
    path: /tmp/debs
    state: directory
# local action
- make_deb:
    recipe: "{{ item }}"
    dest: "{{ playbook_dir }}/debs/{{ item.name }}-{{ item.version }}.deb"
  with_items: "{{ [pipeline2_engine, pipeline2_webui] + pipeline2_extra_modules }}"
- copy:
    src: "{{ playbook_dir }}/debs/{{ item.name }}-{{ item.version }}.deb"
    dest: /tmp/debs/
  with_items: "{{ [pipeline2_engine, pipeline2_webui] + pipeline2_extra_modules }}"
# remove database
- file:
    path: /var/opt/daisy-pipeline2
    state: absent
- shell: DEBIAN_FRONTEND=noninteractive dpkg -i /tmp/debs/*.deb
- template:
    src: opt/daisy-pipeline2/etc/system.properties
    dest: /opt/daisy-pipeline2/etc/system.properties
- service:
    name: "{{ item }}"
    state: started
  with_items:
    - pipeline2d
    - daisy-pipeline2-webui
